import { User } from "./user";

export const USERS:any=[
    {
        id:"1",
        age:23,
        firstName:"Bradford",
        lastName:"Ledner",
        isDeleted:false,
        login:"bradford.ledner",
        password:"TLWPDdozqh"
    },
    {
        id:"2",
        age:51,
        firstName:"Russel",
        lastName:"Ratke",
        isDeleted:true,
        login:"russel.ratke",
        password:"4UlQxVtOMA"
    },
    {
        id:"3",
        age:55,
        firstName:"Mendy",
        lastName:"Schmidt",
        isDeleted:false,
        login:"mendy.schmidt",
        password:"tOBnf0UjK1"
    },
    {
        id:"4",
        age:26,
        firstName:"Edward",
        lastName:"Weber",
        isDeleted:false,
        login:"edward.weber",
        password:"Odtb1fLamP"
    },
    {
        id:"5",
        age:60,
        firstName:"Meagan",
        lastName:"Kiehn",
        isDeleted:false,
        login:"meagan.kiehn",
        password:"BGCJtP401I"
    },
    {
        id:"6",
        age:20,
        firstName:"Angelyn",
        lastName:"Torphy",
        isDeleted:true,
        login:"angelyn.torphy",
        password:"ZwscSFb7iH"
    },
    {
        id:"7",
        age:37,
        firstName:"Kendal",
        lastName:"Bahringer",
        isDeleted:true,
        login:"kendal.bahringer",
        password:"kuvY6ohOBn"
    },
    {
        id:"8",
        age:53,
        firstName:"Stacy",
        lastName:"Buckridge",
        isDeleted:false,
        login:"stacy.buckridge",
        password:"dS2sF8Z5mf"
    },
    {
        id:"9",
        age:57,
        firstName:"Kayleen",
        lastName:"Luettgen",
        isDeleted:true,
        login:"kayleen.luettgen",
        password:"EKHFAijDok"
    },
    {
        id:"10",
        age:63,
        firstName:"Marketta",
        lastName:"Will",
        isDeleted:false,
        login:"marketta.will",
        password:"vr72xBDjZ3"
    },
    {
        id:"11",
        age:35,
        firstName:"Greg",
        lastName:"Doyle",
        isDeleted:false,
        login:"greg.doyle",
        password:"kcj6hlVpKe"
    },
    {
        id:"12",
        age:54,
        firstName:"Bertram",
        lastName:"Collier",
        isDeleted:false,
        login:"bertram.collier",
        password:"fYNrJaW4bB"
    },
    {
        id:"13",
        age:33,
        firstName:"Deshawn",
        lastName:"Sawayn",
        isDeleted:false,
        login:"deshawn.sawayn",
        password:"8dm1lL4Vbf"
    },
    {
        id:"14",
        age:30,
        firstName:"Nathanial",
        lastName:"Mante",
        isDeleted:false,
        login:"nathanial.mante",
        password:"CLnxDpGoZB"
    },
    {
        id:"15",
        age:40,
        firstName:"Will",
        lastName:"Willms",
        isDeleted:false,
        login:"will.willms",
        password:"QXWF2P8Yko"
    },
    {
        id:"16",
        age:25,
        firstName:"Christine",
        lastName:"Swaniawski",
        isDeleted:false,
        login:"christine.swaniawski",
        password:"8GuUBgVnEJ"
    },
    {
        id:"17",
        age:36,
        firstName:"Tierra",
        lastName:"Daugherty",
        isDeleted:false,
        login:"tierra.daugherty",
        password:"trXl6dWkBg"
    },
    {
        id:"18",
        age:40,
        firstName:"Hayley",
        lastName:"Schmitt",
        isDeleted:false,
        login:"tierra.daugherty",
        password:"dmBE0CS3Xy"
    },
    {
        id:"19",
        age:43,
        firstName:"Sean",
        lastName:"Farrell",
        isDeleted:false,
        login:"sean.farrell",
        password:"ApEIDqlTg5"
    },
    {
        id:"20",
        age:36,
        firstName:"Ileen",
        lastName:"Blick",
        isDeleted:false,
        login:"ileen.blick",
        password:"sKAMhtwkXE"
    }
]